using System;
using System.Collections.Generic;

namespace BagproWebAPI.Models
{
    public partial class ProcesoImpresion
    {
        public int Id { get; set; }
        public int Pista { get; set; }
        public int Maquina { get; set; }
        public string Ots1 { get; set; } = null!;
        public string? CodItem1 { get; set; }
        public string? Item1 { get; set; }
        public string? CodCliente1 { get; set; }
        public string? Cliente1 { get; set; }
        public decimal Adj1 { get; set; }
        public decimal Ancho1 { get; set; }
        public decimal? Rodillo1 { get; set; }
        public decimal? Largo1 { get; set; }
        public decimal? Fuelle1 { get; set; }
        public string? Tinta1 { get; set; }
        public string? Tinta2 { get; set; }
        public string? Tinta3 { get; set; }
        public string? Tinta4 { get; set; }
        public string? Tinta5 { get; set; }
        public string? Tinta6 { get; set; }
        public string? Tinta7 { get; set; }
        public string? Tinta8 { get; set; }
        public string? Ots2 { get; set; }
        public string? CodItem2 { get; set; }
        public string? Item2 { get; set; }
        public string? CodCliente2 { get; set; }
        public string? Cliente2 { get; set; }
        public decimal? Adj2 { get; set; }
        public decimal? Ancho2 { get; set; }
        public decimal? Rodillo2 { get; set; }
        public decimal? Largo2 { get; set; }
        public decimal? Fuelle2 { get; set; }
        public string? Tinta12 { get; set; }
        public string? Tinta22 { get; set; }
        public string? Tinta32 { get; set; }
        public string? Tinta42 { get; set; }
        public string? Tinta52 { get; set; }
        public string? Tinta62 { get; set; }
        public string? Tinta72 { get; set; }
        public string? Tinta82 { get; set; }
        public string? Ots3 { get; set; }
        public string? CodItem3 { get; set; }
        public string? Item3 { get; set; }
        public string? CodCliente3 { get; set; }
        public string? Cliente3 { get; set; }
        public decimal? Adj3 { get; set; }
        public decimal? Ancho3 { get; set; }
        public decimal? Rodillo3 { get; set; }
        public decimal? Largo3 { get; set; }
        public decimal? Fuelle3 { get; set; }
        public string? Tinta13 { get; set; }
        public string? Tinta23 { get; set; }
        public string? Tinta33 { get; set; }
        public string? Tinta43 { get; set; }
        public string? Tinta53 { get; set; }
        public string? Tinta63 { get; set; }
        public string? Tinta73 { get; set; }
        public string? Tinta83 { get; set; }
        public string? Ots4 { get; set; }
        public string? CodItem4 { get; set; }
        public string? Item4 { get; set; }
        public string? CodCliente4 { get; set; }
        public string? Cliente4 { get; set; }
        public decimal? Adj4 { get; set; }
        public decimal? Ancho4 { get; set; }
        public decimal? Rodillo4 { get; set; }
        public decimal? Largo4 { get; set; }
        public decimal? Fuelle4 { get; set; }
        public string? Tinta14 { get; set; }
        public string? Tinta24 { get; set; }
        public string? Tinta34 { get; set; }
        public string? Tinta44 { get; set; }
        public string? Tinta54 { get; set; }
        public string? Tinta64 { get; set; }
        public string? Tinta74 { get; set; }
        public string? Tinta84 { get; set; }
        public string? Ots5 { get; set; }
        public string? CodItem5 { get; set; }
        public string? Item5 { get; set; }
        public string? CodCliente5 { get; set; }
        public string? Cliente5 { get; set; }
        public decimal? Adj5 { get; set; }
        public decimal? Ancho5 { get; set; }
        public decimal? Rodillo5 { get; set; }
        public decimal? Largo5 { get; set; }
        public decimal? Fuelle5 { get; set; }
        public string? Tinta15 { get; set; }
        public string? Tinta25 { get; set; }
        public string? Tinta35 { get; set; }
        public string? Tinta45 { get; set; }
        public string? Tinta55 { get; set; }
        public string? Tinta65 { get; set; }
        public string? Tinta75 { get; set; }
        public string? Tinta85 { get; set; }
        public decimal? Qty1 { get; set; }
        public decimal? Qty2 { get; set; }
        public decimal? Qty3 { get; set; }
        public decimal? Qty4 { get; set; }
        public decimal? Qty5 { get; set; }
        public decimal? AnchoPista { get; set; }
        public decimal? TirillaKg { get; set; }
        public decimal? Tirilla { get; set; }
        public int? ItemRollo1 { get; set; }
        public string? RolloMaterila1 { get; set; }
        public decimal? AnchoM1 { get; set; }
        public decimal? CalibreM1 { get; set; }
        public decimal? PesoM1 { get; set; }
        public int? ItemRollo2 { get; set; }
        public string? RolloMaterila2 { get; set; }
        public decimal? AnchoM2 { get; set; }
        public decimal? CalibreM2 { get; set; }
        public decimal? PesoM2 { get; set; }
        public int? ItemRollo3 { get; set; }
        public string? RolloMaterila3 { get; set; }
        public decimal? AnchoM3 { get; set; }
        public decimal? CalibreM3 { get; set; }
        public decimal? PesoM3 { get; set; }
        public int? ItemRollo4 { get; set; }
        public string? RolloMaterila4 { get; set; }
        public decimal? AnchoM4 { get; set; }
        public decimal? CalibreM4 { get; set; }
        public decimal? PesoM4 { get; set; }
        public int? ItemRollo5 { get; set; }
        public string? RolloMaterila5 { get; set; }
        public decimal? AnchoM5 { get; set; }
        public decimal? CalibreM5 { get; set; }
        public decimal? PesoM5 { get; set; }
        public int? ItemRollo6 { get; set; }
        public string? RolloMaterila6 { get; set; }
        public decimal? AnchoM6 { get; set; }
        public decimal? CalibreM6 { get; set; }
        public decimal? PesoM6 { get; set; }
        public int? ItemRollo7 { get; set; }
        public string? RolloMaterila7 { get; set; }
        public decimal? AnchoM7 { get; set; }
        public decimal? CalibreM7 { get; set; }
        public decimal? PesoM7 { get; set; }
        public int? ItemRollo8 { get; set; }
        public string? RolloMaterila8 { get; set; }
        public decimal? AnchoM8 { get; set; }
        public decimal? CalibreM8 { get; set; }
        public decimal? PesoM8 { get; set; }
        public int? ItemRollo9 { get; set; }
        public string? RolloMaterila9 { get; set; }
        public decimal? AnchoM9 { get; set; }
        public decimal? CalibreM9 { get; set; }
        public decimal? PesoM9 { get; set; }
        public int? ItemRollo10 { get; set; }
        public string? RolloMaterila10 { get; set; }
        public decimal? AnchoM10 { get; set; }
        public decimal? CalibreM10 { get; set; }
        public decimal? PesoM10 { get; set; }
        public int? ItemRollo11 { get; set; }
        public string? RolloMaterila11 { get; set; }
        public decimal? AnchoM11 { get; set; }
        public decimal? CalibreM11 { get; set; }
        public decimal? PesoM11 { get; set; }
        public int? ItemRollo12 { get; set; }
        public string? RolloMaterila12 { get; set; }
        public decimal? AnchoM12 { get; set; }
        public decimal? CalibreM12 { get; set; }
        public decimal? PesoM12 { get; set; }
        public int? ItemRollo13 { get; set; }
        public string? RolloMaterila13 { get; set; }
        public decimal? AnchoM13 { get; set; }
        public decimal? CalibreM13 { get; set; }
        public decimal? PesoM13 { get; set; }
        public int? ItemRollo14 { get; set; }
        public string? RolloMaterila14 { get; set; }
        public decimal? AnchoM14 { get; set; }
        public decimal? CalibreM14 { get; set; }
        public decimal? PesoM14 { get; set; }
        public int? ItemRollo15 { get; set; }
        public string? RolloMaterila15 { get; set; }
        public decimal? AnchoM15 { get; set; }
        public decimal? CalibreM15 { get; set; }
        public decimal? PesoM15 { get; set; }
        public int? ItemRollo16 { get; set; }
        public string? RolloMaterila16 { get; set; }
        public decimal? AnchoM16 { get; set; }
        public decimal? CalibreM16 { get; set; }
        public decimal? PesoM16 { get; set; }
        public int? ItemRollo17 { get; set; }
        public string? RolloMaterila17 { get; set; }
        public decimal? AnchoM17 { get; set; }
        public decimal? CalibreM17 { get; set; }
        public decimal? PesoM17 { get; set; }
        public int? ItemRollo18 { get; set; }
        public string? RolloMaterila18 { get; set; }
        public decimal? AnchoM18 { get; set; }
        public decimal? CalibreM18 { get; set; }
        public decimal? PesoM18 { get; set; }
        public int? ItemRollo19 { get; set; }
        public string? RolloMaterila19 { get; set; }
        public decimal? AnchoM19 { get; set; }
        public decimal? CalibreM19 { get; set; }
        public decimal? PesoM19 { get; set; }
        public int? ItemRollo20 { get; set; }
        public string? RolloMaterila20 { get; set; }
        public decimal? AnchoM20 { get; set; }
        public decimal? CalibreM20 { get; set; }
        public decimal? PesoM20 { get; set; }
        public int? ItemRollo21 { get; set; }
        public string? RolloMaterila21 { get; set; }
        public decimal? AnchoM21 { get; set; }
        public decimal? CalibreM21 { get; set; }
        public decimal? PesoM21 { get; set; }
        public int? ItemRollo22 { get; set; }
        public string? RolloMaterila22 { get; set; }
        public decimal? AnchoM22 { get; set; }
        public decimal? CalibreM22 { get; set; }
        public decimal? PesoM22 { get; set; }
        public int? ItemRollo23 { get; set; }
        public string? RolloMaterila23 { get; set; }
        public decimal? AnchoM23 { get; set; }
        public decimal? CalibreM23 { get; set; }
        public decimal? PesoM23 { get; set; }
        public int? ItemRollo24 { get; set; }
        public string? RolloMaterila24 { get; set; }
        public decimal? AnchoM24 { get; set; }
        public decimal? CalibreM24 { get; set; }
        public decimal? PesoM24 { get; set; }
        public int? ItemRollo25 { get; set; }
        public string? RolloMaterila25 { get; set; }
        public decimal? AnchoM25 { get; set; }
        public decimal? CalibreM25 { get; set; }
        public decimal? PesoM25 { get; set; }
        public int? ItemRollo26 { get; set; }
        public string? RolloMaterila26 { get; set; }
        public decimal? AnchoM26 { get; set; }
        public decimal? CalibreM26 { get; set; }
        public decimal? PesoM26 { get; set; }
        public int? ItemRollo27 { get; set; }
        public string? RolloMaterila27 { get; set; }
        public decimal? AnchoM27 { get; set; }
        public decimal? CalibreM27 { get; set; }
        public decimal? PesoM27 { get; set; }
        public int? ItemRollo28 { get; set; }
        public string? RolloMaterila28 { get; set; }
        public decimal? AnchoM28 { get; set; }
        public decimal? CalibreM28 { get; set; }
        public decimal? PesoM28 { get; set; }
        public int? ItemRollo29 { get; set; }
        public string? RolloMaterila29 { get; set; }
        public decimal? AnchoM29 { get; set; }
        public decimal? CalibreM29 { get; set; }
        public decimal? PesoM29 { get; set; }
        public int? ItemRollo30 { get; set; }
        public string? RolloMaterila30 { get; set; }
        public decimal? AnchoM30 { get; set; }
        public decimal? CalibreM30 { get; set; }
        public decimal? PesoM30 { get; set; }
        public int? ItemRollo31 { get; set; }
        public string? RolloMaterila31 { get; set; }
        public decimal? AnchoM31 { get; set; }
        public decimal? CalibreM31 { get; set; }
        public decimal? PesoM31 { get; set; }
        public int? ItemRollo32 { get; set; }
        public string? RolloMaterila32 { get; set; }
        public decimal? AnchoM32 { get; set; }
        public decimal? CalibreM32 { get; set; }
        public decimal? PesoM32 { get; set; }
        public int? ItemRollo33 { get; set; }
        public string? RolloMaterila33 { get; set; }
        public decimal? AnchoM33 { get; set; }
        public decimal? CalibreM33 { get; set; }
        public decimal? PesoM33 { get; set; }
        public int? ItemRollo34 { get; set; }
        public string? RolloMaterila34 { get; set; }
        public decimal? AnchoM34 { get; set; }
        public decimal? CalibreM34 { get; set; }
        public decimal? PesoM34 { get; set; }
        public int? ItemRollo35 { get; set; }
        public string? RolloMaterila35 { get; set; }
        public decimal? AnchoM35 { get; set; }
        public decimal? CalibreM35 { get; set; }
        public decimal? PesoM35 { get; set; }
        public int? ItemRollo36 { get; set; }
        public string? RolloMaterila36 { get; set; }
        public decimal? AnchoM36 { get; set; }
        public decimal? CalibreM36 { get; set; }
        public decimal? PesoM36 { get; set; }
        public int? ItemRollo37 { get; set; }
        public string? RolloMaterila37 { get; set; }
        public decimal? AnchoM37 { get; set; }
        public decimal? CalibreM37 { get; set; }
        public decimal? PesoM37 { get; set; }
        public int? ItemRollo38 { get; set; }
        public string? RolloMaterila38 { get; set; }
        public decimal? AnchoM38 { get; set; }
        public decimal? CalibreM38 { get; set; }
        public decimal? PesoM38 { get; set; }
        public int? ItemRollo39 { get; set; }
        public string? RolloMaterila39 { get; set; }
        public decimal? AnchoM39 { get; set; }
        public decimal? CalibreM39 { get; set; }
        public decimal? PesoM39 { get; set; }
        public int? ItemRollo40 { get; set; }
        public string? RolloMaterila40 { get; set; }
        public decimal? AnchoM40 { get; set; }
        public decimal? CalibreM40 { get; set; }
        public decimal? PesoM40 { get; set; }
        public int? ItemRollo41 { get; set; }
        public string? RolloMaterila41 { get; set; }
        public decimal? AnchoM41 { get; set; }
        public decimal? CalibreM41 { get; set; }
        public decimal? PesoM41 { get; set; }
        public int? ItemRollo42 { get; set; }
        public string? RolloMaterila42 { get; set; }
        public decimal? AnchoM42 { get; set; }
        public decimal? CalibreM42 { get; set; }
        public decimal? PesoM42 { get; set; }
        public int? ItemRollo43 { get; set; }
        public string? RolloMaterila43 { get; set; }
        public decimal? AnchoM43 { get; set; }
        public decimal? CalibreM43 { get; set; }
        public decimal? PesoM43 { get; set; }
        public int? ItemRollo44 { get; set; }
        public string? RolloMaterila44 { get; set; }
        public decimal? AnchoM44 { get; set; }
        public decimal? CalibreM44 { get; set; }
        public decimal? PesoM44 { get; set; }
        public int? ItemRollo45 { get; set; }
        public string? RolloMaterila45 { get; set; }
        public decimal? AnchoM45 { get; set; }
        public decimal? CalibreM45 { get; set; }
        public decimal? PesoM45 { get; set; }
        public int? ItemRollo46 { get; set; }
        public string? RolloMaterila46 { get; set; }
        public decimal? AnchoM46 { get; set; }
        public decimal? CalibreM46 { get; set; }
        public decimal? PesoM46 { get; set; }
        public int? ItemRollo47 { get; set; }
        public string? RolloMaterila47 { get; set; }
        public decimal? AnchoM47 { get; set; }
        public decimal? CalibreM47 { get; set; }
        public decimal? PesoM47 { get; set; }
        public int? ItemRollo48 { get; set; }
        public string? RolloMaterila48 { get; set; }
        public decimal? AnchoM48 { get; set; }
        public decimal? CalibreM48 { get; set; }
        public decimal? PesoM48 { get; set; }
        public int? ItemRollo49 { get; set; }
        public string? RolloMaterila49 { get; set; }
        public decimal? AnchoM49 { get; set; }
        public decimal? CalibreM49 { get; set; }
        public decimal? PesoM49 { get; set; }
        public int? ItemRollo50 { get; set; }
        public string? RolloMaterila50 { get; set; }
        public decimal? AnchoM50 { get; set; }
        public decimal? CalibreM50 { get; set; }
        public decimal? PesoM50 { get; set; }
        public string UsrCrea { get; set; } = null!;
        public DateTime Fecha { get; set; }
        public int? Estado { get; set; }
    }
}
